[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "pytick"
version = "0.3.0"
requires-python = ">=3.11"
dependencies = ["numpy", "matplotlib"]

[project.optional-dependencies]
viz = ["matplotlib"]
dev = ["pytest"]

[tool.scikit-build]
build-dir = "build/{wheel_tag}"

[tool.pytest.ini_options]
testpaths = ["tests"]
